/**
 * buildings.js — Building definitions for Virtual Luxury City
 */

const BUILDINGS = {
  // ── Residential ─────────────────────────────────────────
  luxury_apt: {
    id: 'luxury_apt',
    name: 'Luxury Apartment',
    category: 'residential',
    icon: '🏠',
    emoji: '🏠',
    color: '#3b82f6',
    cost: 50_000,
    upkeep: 500,
    income: 2_000,
    population: 50,
    prestige: 5,
    happiness: 5,
    size: 1,
    desc: 'Upscale apartments for the elite.',
    unlockPrestige: 0,
  },
  penthouse_tower: {
    id: 'penthouse_tower',
    name: 'Penthouse Tower',
    category: 'residential',
    icon: '🏢',
    emoji: '🏢',
    color: '#6366f1',
    cost: 250_000,
    upkeep: 2_500,
    income: 12_000,
    population: 200,
    prestige: 25,
    happiness: 10,
    size: 2,
    desc: 'Sky-high penthouses with panoramic views.',
    unlockPrestige: 20,
  },
  mega_mansion: {
    id: 'mega_mansion',
    name: 'Mega Mansion',
    category: 'residential',
    icon: '🏰',
    emoji: '🏰',
    color: '#8b5cf6',
    cost: 750_000,
    upkeep: 8_000,
    income: 35_000,
    population: 50,
    prestige: 80,
    happiness: 20,
    size: 3,
    desc: 'The ultimate symbol of wealth and luxury.',
    unlockPrestige: 100,
  },

  // ── Commercial ──────────────────────────────────────────
  boutique: {
    id: 'boutique',
    name: 'Luxury Boutique',
    category: 'commercial',
    icon: '👗',
    emoji: '👗',
    color: '#ec4899',
    cost: 30_000,
    upkeep: 300,
    income: 3_000,
    population: 0,
    prestige: 8,
    happiness: 3,
    size: 1,
    desc: 'High-end fashion and designer goods.',
    unlockPrestige: 0,
  },
  grand_hotel: {
    id: 'grand_hotel',
    name: 'Grand Hotel',
    category: 'commercial',
    icon: '🏨',
    emoji: '🏨',
    color: '#f59e0b',
    cost: 400_000,
    upkeep: 5_000,
    income: 25_000,
    population: 0,
    prestige: 50,
    happiness: 15,
    size: 3,
    desc: 'Five-star hospitality for distinguished guests.',
    unlockPrestige: 50,
  },
  casino: {
    id: 'casino',
    name: 'Diamond Casino',
    category: 'commercial',
    icon: '🎰',
    emoji: '🎰',
    color: '#ef4444',
    cost: 600_000,
    upkeep: 10_000,
    income: 50_000,
    population: 0,
    prestige: 70,
    happiness: 10,
    size: 3,
    desc: 'High-stakes gaming and entertainment palace.',
    unlockPrestige: 80,
  },
  yacht_club: {
    id: 'yacht_club',
    name: 'Yacht Club',
    category: 'commercial',
    icon: '⛵',
    emoji: '⛵',
    color: '#06b6d4',
    cost: 500_000,
    upkeep: 7_000,
    income: 30_000,
    population: 0,
    prestige: 90,
    happiness: 25,
    size: 2,
    desc: 'Exclusive marina for the sailing elite.',
    unlockPrestige: 120,
  },

  // ── Finance ─────────────────────────────────────────────
  bank: {
    id: 'bank',
    name: 'Private Bank',
    category: 'finance',
    icon: '🏦',
    emoji: '🏦',
    color: '#10b981',
    cost: 200_000,
    upkeep: 2_000,
    income: 15_000,
    population: 0,
    prestige: 30,
    happiness: 0,
    size: 2,
    desc: 'Manages the city\'s wealth discreetly.',
    unlockPrestige: 30,
  },
  stock_exchange: {
    id: 'stock_exchange',
    name: 'Stock Exchange',
    category: 'finance',
    icon: '📈',
    emoji: '📈',
    color: '#22c55e',
    cost: 1_000_000,
    upkeep: 15_000,
    income: 100_000,
    population: 0,
    prestige: 150,
    happiness: 5,
    size: 3,
    desc: 'Drives the city\'s financial empire.',
    unlockPrestige: 200,
  },

  // ── Entertainment ────────────────────────────────────────
  opera_house: {
    id: 'opera_house',
    name: 'Opera House',
    category: 'entertainment',
    icon: '🎭',
    emoji: '🎭',
    color: '#a855f7',
    cost: 350_000,
    upkeep: 4_000,
    income: 10_000,
    population: 0,
    prestige: 60,
    happiness: 30,
    size: 3,
    desc: 'World-class performances for cultured citizens.',
    unlockPrestige: 60,
  },
  art_gallery: {
    id: 'art_gallery',
    name: 'Art Gallery',
    category: 'entertainment',
    icon: '🖼',
    emoji: '🖼',
    color: '#e879f9',
    cost: 120_000,
    upkeep: 1_500,
    income: 5_000,
    population: 0,
    prestige: 35,
    happiness: 20,
    size: 2,
    desc: 'Showcases masterpieces from around the world.',
    unlockPrestige: 40,
  },
  rooftop_bar: {
    id: 'rooftop_bar',
    name: 'Rooftop Lounge',
    category: 'entertainment',
    icon: '🍸',
    emoji: '🍸',
    color: '#f97316',
    cost: 80_000,
    upkeep: 800,
    income: 6_000,
    population: 0,
    prestige: 20,
    happiness: 15,
    size: 1,
    desc: 'Sky-level cocktails with breathtaking views.',
    unlockPrestige: 15,
  },

  // ── Infrastructure ───────────────────────────────────────
  helipad: {
    id: 'helipad',
    name: 'Private Helipad',
    category: 'infrastructure',
    icon: '🚁',
    emoji: '🚁',
    color: '#64748b',
    cost: 100_000,
    upkeep: 2_000,
    income: 0,
    population: 0,
    prestige: 40,
    happiness: 5,
    size: 1,
    desc: 'VIP air transport for the privileged few.',
    unlockPrestige: 50,
  },
  solar_plant: {
    id: 'solar_plant',
    name: 'Solar Power Plant',
    category: 'infrastructure',
    icon: '☀️',
    emoji: '☀️',
    color: '#fbbf24',
    cost: 180_000,
    upkeep: 500,
    income: 5_000,
    population: 0,
    prestige: 20,
    happiness: 10,
    size: 2,
    desc: 'Clean energy for a sustainable luxury city.',
    unlockPrestige: 25,
  },

  // ── Parks & Leisure ──────────────────────────────────────
  zen_garden: {
    id: 'zen_garden',
    name: 'Zen Garden',
    category: 'park',
    icon: '🌿',
    emoji: '🌿',
    color: '#4ade80',
    cost: 20_000,
    upkeep: 200,
    income: 0,
    population: 0,
    prestige: 10,
    happiness: 20,
    size: 1,
    desc: 'Serene green space for tranquil reflection.',
    unlockPrestige: 0,
  },
  olympic_spa: {
    id: 'olympic_spa',
    name: 'Olympic Spa',
    category: 'park',
    icon: '🧖',
    emoji: '🧖',
    color: '#2dd4bf',
    cost: 220_000,
    upkeep: 3_000,
    income: 12_000,
    population: 0,
    prestige: 45,
    happiness: 35,
    size: 2,
    desc: 'World-class wellness and relaxation centre.',
    unlockPrestige: 55,
  },
  private_beach: {
    id: 'private_beach',
    name: 'Private Beach',
    category: 'park',
    icon: '🏖',
    emoji: '🏖',
    color: '#fb923c',
    cost: 300_000,
    upkeep: 2_500,
    income: 8_000,
    population: 0,
    prestige: 55,
    happiness: 40,
    size: 3,
    desc: 'Exclusive beachfront reserved for residents.',
    unlockPrestige: 70,
  },

  // ── Landmark ─────────────────────────────────────────────
  golden_tower: {
    id: 'golden_tower',
    name: 'Golden Tower',
    category: 'landmark',
    icon: '🗼',
    emoji: '🗼',
    color: '#c9a84c',
    cost: 2_000_000,
    upkeep: 20_000,
    income: 80_000,
    population: 0,
    prestige: 300,
    happiness: 50,
    size: 3,
    desc: 'The crown jewel of Luxuria — visible for miles.',
    unlockPrestige: 300,
  },
};

/** Categories with display info */
const CATEGORIES = {
  residential:    { label: 'Residential',    icon: '🏠' },
  commercial:     { label: 'Commercial',     icon: '🏪' },
  finance:        { label: 'Finance',        icon: '💹' },
  entertainment:  { label: 'Entertainment',  icon: '🎉' },
  infrastructure: { label: 'Infrastructure', icon: '⚙️' },
  park:           { label: 'Parks',          icon: '🌳' },
  landmark:       { label: 'Landmarks',      icon: '🏛' },
};
